config-1:
    param: true
    params:
    - val1
    - val2
    -   in1: vl1
    dict:
        k1: v1
        k2: 11
        k3:
            v1: v1
            v2:
            - v0
            - v1
    k1: ('v3', 'v4')
k1:
    k11: v1
    k22:
    - 1
    - 3
    - '5'
config-2:
    p1: 11.0
    p2:
    - 11
    - 2
    - 32
