# root comment
config-1:   # config-1 comment
  param: 'True'     # param comment
  params:
  - val2
  -  in1: vl1
  - new
  - new1
  dict:
    k1: v1        # k1 same name comment
    k2: 11
    k3:
      v1: v1
      v2:
      - v0
      - v1        # list element comment
  k1: False     # k1 same name comment
# breaking comment
k1:
  k11: v1
  k22:
  - 1
  - 3
  - '5'
config-2:         # config-2 comment
  p1: 11.0
  p2:
  - 11
  - 2
  - 32
